### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by janosdebugs** [arcalot/arcaflow-plugins-incubator#2]
We need a build system that can build the plugins in the respective folders, and then check them for compliance with the plugin requirements. If run on the main branch, the images should also be pushed to Quay.

1. - [x] build an image given a directory of plugin directories (sub-directories, each with a dockerfile)
2. - [X] build every image given a directory of plugin directories
3. - [X] build an image given a plugin directory
4. - [X] add readme
5. - [X] check plugin source directory for compliance with requirements
6. - [x] push a built image to at least one registry
7. - [X] containerize 
8. - [X] add github action to carpenter's repo that executes carpenter on caller
9. - [X] add github action trigger to plugin template repo to use carpenter's github action
10. - [X] push an image to ghcr.io or quay.io
11. - [X] push an image with quay robot credentials
12. - [X] make [python plugin template](https://github.com/arcalot/arcaflow-plugin-template-python) pass build requirements
13. - [X] make separate repo for [python plugin fio](https://github.com/arcalot/arcaflow-plugins/tree/main/python/fio) and make it passes build requirements
14. - [X] allow for semantic versioning of image tags
16. - [X] manage the version of a plugin
17. - [X] check plugin source code for python code style format
18. - [x] check plugin source code for python code quality

**Comment by mfleader** [comment]
At the moment, can only check python code style, but not golang code style. Will add golang code style checking when we have golang plugins.

**Comment by dustinblack** [comment]
@mfleader Where are we on the task items here? Can you provide an update?
