### ISSUE TITLE
Plugin(s) to replace Litmus-powered chaos scenarios

### ISSUE THREAD

**Issue by dustinblack** [arcalot/arcaflow-plugins-incubator#49]
## Please describe what you would like to see in this project

We need a plugin or multiple plugins that can adequately replace the scenarios in [Krkn](https://github.com/redhat-chaos/krkn) currently powered by the external [Litmus](https://github.com/litmuschaos/litmus) project. 

## Please describe your use case

Litmus uses operators currently, which goes against the Krkn goal of operating all load tests from orchestration outside of the cluster. Krkn currently [leverages the CPU, memory, and I/O hog functionalities](https://github.com/redhat-chaos/krkn/blob/main/docs/litmus_scenarios.md) of Litmus.

## Additional context

 It's possible that we can simply replace the Litmus loads with those from stressng, sysbench, and/or fio, which we already support, but work needs to be done to ensure that we can provide comparable or better functionality.

**Comment by chaitanyaenr** [comment]
Fixes https://github.com/redhat-chaos/krkn/issues/291. Thanks.

**Comment by dustinblack** [comment]
Closing as effort moved to redhat-chaos
